version: "3"

services: 
  db:
    image: mariadb:10.4
    restart: always
    environment: 
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=backendhibrido
    ports: 
      - 8002:3306
    volumes: 
      - ./db_data:/etc/mysql/conf.d

  app:
    image: carloscarrinho/webserverphp:1.1
    volumes: 
      - ./:/var/www/html
    ports: 
      - 8001:80
    links:
      - db
    depends_on: 
      - db
    tty: true